### ISSUE TITLE
Visualizing Data with mapbox-gl branch

### ISSUE THREAD

**Issue by Craytor** [kylehotchkiss/grads#23]
Hello!

I've went ahead, cloned, checked out the mapbox-gl branch, npm installed, and then ```node index.js```'ed. I went to the browser to try it out at ```localhost:3000``` and it say's ```loading``` for each of the values. I checked the log in the console and I'm presented with the following error:

```
TypeError: Cannot read property 'indexOf' of undefined
    at Sea.Grads (/Users/craytor/Code/Tinker/grads/library/grads.js:140:17)
    at Sea (/Users/craytor/Code/Tinker/grads/library/abstractions/sea.js:13:9)
    at /Users/craytor/Code/Tinker/grads/index.js:50:18
    at Layer.handle [as handle_request] (/Users/craytor/Code/Tinker/grads/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/craytor/Code/Tinker/grads/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/craytor/Code/Tinker/grads/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/craytor/Code/Tinker/grads/node_modules/express/lib/router/layer.js:95:5)
    at /Users/craytor/Code/Tinker/grads/node_modules/express/lib/router/index.js:277:22
    at param (/Users/craytor/Code/Tinker/grads/node_modules/express/lib/router/index.js:349:14)
    at param (/Users/craytor/Code/Tinker/grads/node_modules/express/lib/router/index.js:365:14)
```

Any suggestions? Thanks!

**Comment by kylehotchkiss** [comment]
Hi @Craytor! Thanks for your interest! I don't maintain this code anymore, It wasn't too efficient (see my use of `eval`) and I couldn't verify its accuracy due to my lack of knowlege of querying gridded binary data

I sadly am not sure which way to send you to play with Gridded binary data, as I couldn't find any suitable tools when I built this so i hacked this project together. I hope somebody can create a Graphql interface for it someday though so people like us could make an awesome mapboxql weather/climate visualization.
